# Main configuration file

mlflow:
  # Experiment name for MLFlow: "model name"_"dataset type"_"dataset name"_"data encoding type"
  experiment_name: '${models.model.name}_${data.dataset_type}_${data.dataset.root}_${data.coding_type}'
  # Path to MLFlow tracking DataBase file
  tracking_uri: 'sqlite:///${hydra:runtime.cwd}/mlflow/mlruns.db'
  # Save examples of conjugacy matrices
  save_adjacency_matrices: True
  # Take the number of elements from max(len, max_elements)
  # If the sample length is greater than max_elements, then sample max_elements with random values
  max_elements: 5
  # Name of seaborn palette for rendering adjacency matrices
  palette_name: 'coolwarm'


# We prohibit hydra from changing the working directory and creating subdirectories
hydra:
  job:
    chdir: False
  run:
    dir: .

defaults:
  - data: config
  - models: config
  # Config from this file override the values of configs from the Defaults List
  - _self_
