# Основной конфигурационный файл

# Запрещаем гидре менять рабочий каталог и создавать подкаталоги
hydra:
  job:
    chdir: False
  run:
    dir: .

defaults:
  - data: config
  - models: config
  # Config from this file override the values of configs from the Defaults List
  - _self_
