# Configuration file for hyperparameter tuning
# Run it instead of config.yaml
mlflow:
  # Experiment name for MLFlow: "model name"_"dataset type"_"dataset name"_"data encoding type"
  experiment_name: '${models.model.name}_${data.dataset_type}_${data.dataset.root}_${data.coding_type}'
  # Path to MLFlow tracking DataBase file
  tracking_uri: 'sqlite:///${hydra:runtime.cwd}/mlflow/mlruns.db'
  # Save examples of conjugacy matrices
  save_adjacency_matrices: False

hydra:
 run:
  dir: hp_search/${now:%Y-%m-%d}/${now:%H-%M-%S}
 sweeper:
   sampler:
     seed: ${models.random_state}
   direction: maximize  # We maximize, because we optimize on the accuracy metric
   study_name: main_acc
   storage: null
   n_trials: 40
   n_jobs: 1
   params:
     models.model.params.hidden_channels: int(interval(8, 32))
     models.model.params.dropout: range(0.05, 0.6, step=0.05)
# global_max_pool always give the best result, so we use it
#     models.model.params.pooling_type: choice('global_max_pool', 'global_mean_pool')


debug: True

defaults:
  - data: config
  - models: config
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # Config from this file override the values of configs from the Defaults List
  - _self_
