# Конфигурационный файл для подбора гиперпараметров
# Запускается вместо config.yaml
mlflow:
  # Название эксперимента для MLFlow: "название модели"_"тип датасета"_"название датасета"_"тип кодирования данных"
  experiment_name: '${models.model.name}_${data.dataset_type}_${data.dataset.root}_${data.coding_type}'
  # Место сохранения БД MLFlow
  tracking_uri: 'sqlite:///${hydra:runtime.cwd}/mlflow/mlruns.db'
  # Сохранять примеры матриц сопряженности
  save_adjacency_matrices: False

hydra:
 run:
  dir: hp_search/${now:%Y-%m-%d}/${now:%H-%M-%S}
 sweeper:
   sampler:
     seed: ${models.random_state}
   direction: maximize  # Максимизируем, т.к. оптимизируемся на метрике accuracy
   study_name: main_acc
   storage: null
   n_trials: 40
   n_jobs: 1
   params:
     models.model.params.hidden_channels: int(interval(8, 32))
     models.model.params.dropout: range(0.05, 0.6, step=0.05)
#     models.model.params.pooling_type: choice('global_max_pool', 'global_mean_pool')


debug: True

defaults:
  - data: config
  - models: config
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # Устанавливаем лаунчер joblib только, если готова папка processed (для первого прогона комментируем)
  #- override hydra/launcher: joblib
  # Config from this file override the values of configs from the Defaults List
  - _self_
